default:
  image: node
  before_script:
    - npm install

stages:
  - code-quality
  - test
  - deploy

lint-job:
  stage: code-quality
  script:
    - echo "Running linter..."
    - npm run lint
    - echo "Lint complete."

format-job:
  stage: code-quality
  script:
    - echo "Checking code formatting..."
    - npx prettier --check src/ cypress
    - echo "Finished checking code format."

unit-test-job:
  stage: test
  script:
    - echo "Running unit tests..."
    - npx vitest --mode development
    - echo "Finished running unit tests."

e2e-test-job:
  stage: test
  image: cypress/base:18.16.0
  script:
    - echo "Running end to end tests..."
    - npm run test:e2e
    - echo "Finished running end to end tests."

deploy:
  stage: deploy
  script:
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh

    - eval `ssh-agent -s`
    - chmod 400 $SSH_PRIVATE_KEY
    - ssh-add $SSH_PRIVATE_KEY

    - npm build
    - scp -o StrictHostKeyChecking=no -o PasswordAuthentication=no -r dist/* freshify@freshify.no:/var/www/freshify.no
