/* tslint:disable */
/* eslint-disable */
/**
 * Freshify API Documentation
 * An API for creating and managing a household inventory and shopping list. The API is written in Java using the Spring Boot framework. The API uses a MySQL database. The API is documented using Swagger. The API is hosted using Apache. Some useful links: - [The GitLab repository](https://gitlab.stud.idi.ntnu.no/idatt2106-v23-10/smartmat-backend)
 *
 * OpenAPI spec version: 2.2.1
 * Contact: vkbugge@hotmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import {Household} from "./household";
import {RecipeDTO} from "./recipe-dto";

/**
 *
 * @export
 * @interface HouseholdRecipeDTO
 */
export interface HouseholdRecipeDTO {
  /**
   *
   * @type {number}
   * @memberof HouseholdRecipeDTO
   */
  id?: number;
  /**
   *
   * @type {RecipeDTO}
   * @memberof HouseholdRecipeDTO
   */
  recipe?: RecipeDTO;
  /**
   *
   * @type {Household}
   * @memberof HouseholdRecipeDTO
   */
  household?: Household;
}
