/* tslint:disable */
/* eslint-disable */
/**
 * Freshify API Documentation
 * An API for creating and managing a household inventory and shopping list. The API is written in Java using the Spring Boot framework. The API uses a MySQL database. The API is documented using Swagger. The API is hosted using Apache. Some useful links: - [The GitLab repository](https://gitlab.stud.idi.ntnu.no/idatt2106-v23-10/smartmat-backend)
 *
 * OpenAPI spec version: 2.2.1
 * Contact: vkbugge@hotmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import {RecipeDTOPagePageableSort} from "./recipe-dtopage-pageable-sort";

/**
 *
 * @export
 * @interface RecipeDTOPagePageable
 */
export interface RecipeDTOPagePageable {
  /**
   *
   * @type {RecipeDTOPagePageableSort}
   * @memberof RecipeDTOPagePageable
   */
  sort?: RecipeDTOPagePageableSort;
  /**
   *
   * @type {number}
   * @memberof RecipeDTOPagePageable
   */
  offset?: number;
  /**
   *
   * @type {number}
   * @memberof RecipeDTOPagePageable
   */
  pageSize?: number;
  /**
   *
   * @type {number}
   * @memberof RecipeDTOPagePageable
   */
  pageNumber?: number;
  /**
   *
   * @type {boolean}
   * @memberof RecipeDTOPagePageable
   */
  paged?: boolean;
  /**
   *
   * @type {boolean}
   * @memberof RecipeDTOPagePageable
   */
  unpaged?: boolean;
}
