/* tslint:disable */
/* eslint-disable */
/**
 * Freshify API Documentation
 * An API for creating and managing a household inventory and shopping list. The API is written in Java using the Spring Boot framework. The API uses a MySQL database. The API is documented using Swagger. The API is hosted using Apache. Some useful links: - [The GitLab repository](https://gitlab.stud.idi.ntnu.no/idatt2106-v23-10/smartmat-backend)
 *
 * OpenAPI spec version: 2.1.2
 * Contact: vkbugge@hotmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import globalAxios, { AxiosResponse, AxiosInstance, AxiosRequestConfig } from "axios";
import { Configuration } from "../configuration";
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from "../base";
import { ItemType } from "../models";
/**
 * ItemTypeApi - axios parameter creator
 * @export
 */
export const ItemTypeApiAxiosParamCreator = function (configuration?: Configuration) {
  return {
    /**
     *
     * @summary Search through item types
     * @param {string} name Search string to find item types by name
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    searchItemTypes: async (
      name: string,
      options: AxiosRequestConfig = {}
    ): Promise<RequestArgs> => {
      // verify required parameter 'name' is not null or undefined
      if (name === null || name === undefined) {
        throw new RequiredError(
          "name",
          "Required parameter name was null or undefined when calling searchItemTypes."
        );
      }
      const localVarPath = `/itemtype`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, "https://example.com");
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }
      const localVarRequestOptions: AxiosRequestConfig = {
        method: "GET",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      if (name !== undefined) {
        localVarQueryParameter["name"] = name;
      }

      const query = new URLSearchParams(localVarUrlObj.search);
      for (const key in localVarQueryParameter) {
        query.set(key, localVarQueryParameter[key]);
      }
      for (const key in options.params) {
        query.set(key, options.params[key]);
      }
      localVarUrlObj.search = new URLSearchParams(query).toString();
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
        options: localVarRequestOptions,
      };
    },
  };
};

/**
 * ItemTypeApi - functional programming interface
 * @export
 */
export const ItemTypeApiFp = function (configuration?: Configuration) {
  return {
    /**
     *
     * @summary Search through item types
     * @param {string} name Search string to find item types by name
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async searchItemTypes(
      name: string,
      options?: AxiosRequestConfig
    ): Promise<
      (axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<Array<ItemType>>>
    > {
      const localVarAxiosArgs = await ItemTypeApiAxiosParamCreator(configuration).searchItemTypes(
        name,
        options
      );
      return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
        const axiosRequestArgs: AxiosRequestConfig = {
          ...localVarAxiosArgs.options,
          url: basePath + localVarAxiosArgs.url,
        };
        return axios.request(axiosRequestArgs);
      };
    },
  };
};

/**
 * ItemTypeApi - factory interface
 * @export
 */
export const ItemTypeApiFactory = function (
  configuration?: Configuration,
  basePath?: string,
  axios?: AxiosInstance
) {
  return {
    /**
     *
     * @summary Search through item types
     * @param {string} name Search string to find item types by name
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async searchItemTypes(
      name: string,
      options?: AxiosRequestConfig
    ): Promise<AxiosResponse<Array<ItemType>>> {
      return ItemTypeApiFp(configuration)
        .searchItemTypes(name, options)
        .then((request) => request(axios, basePath));
    },
  };
};

/**
 * ItemTypeApi - object-oriented interface
 * @export
 * @class ItemTypeApi
 * @extends {BaseAPI}
 */
export class ItemTypeApi extends BaseAPI {
  /**
   *
   * @summary Search through item types
   * @param {string} name Search string to find item types by name
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof ItemTypeApi
   */
  public async searchItemTypes(
    name: string,
    options?: AxiosRequestConfig
  ): Promise<AxiosResponse<Array<ItemType>>> {
    return ItemTypeApiFp(this.configuration)
      .searchItemTypes(name, options)
      .then((request) => request(this.axios, this.basePath));
  }
}
