/* tslint:disable */
/* eslint-disable */
/**
 * Freshify API Documentation
 * An API for creating and managing a household inventory and shopping list. The API is written in Java using the Spring Boot framework. The API uses a MySQL database. The API is documented using Swagger. The API is hosted using Apache. Some useful links: - [The GitLab repository](https://gitlab.stud.idi.ntnu.no/idatt2106-v23-10/smartmat-backend)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: vkbugge@hotmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import globalAxios, { AxiosResponse, AxiosInstance, AxiosRequestConfig } from "axios";
import { Configuration } from "../configuration";
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from "../base";
import { Recipe } from "../models";
import { RecipeRequest } from "../models";
/**
 * RecipesApi - axios parameter creator
 * @export
 */
export const RecipesApiAxiosParamCreator = function (configuration?: Configuration) {
  return {
    /**
     * Creates a new recipe and saves to backend.
     * @summary Create a new recipe
     * @param {RecipeRequest} body Recipe object to be created and saved.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    createRecipe: async (
      body: RecipeRequest,
      options: AxiosRequestConfig = {}
    ): Promise<RequestArgs> => {
      // verify required parameter 'body' is not null or undefined
      if (body === null || body === undefined) {
        throw new RequiredError(
          "body",
          "Required parameter body was null or undefined when calling createRecipe."
        );
      }
      const localVarPath = `/recipes`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, "https://example.com");
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }
      const localVarRequestOptions: AxiosRequestConfig = {
        method: "POST",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      localVarHeaderParameter["Content-Type"] = "application/json";

      const query = new URLSearchParams(localVarUrlObj.search);
      for (const key in localVarQueryParameter) {
        query.set(key, localVarQueryParameter[key]);
      }
      for (const key in options.params) {
        query.set(key, options.params[key]);
      }
      localVarUrlObj.search = new URLSearchParams(query).toString();
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };
      const needsSerialization =
        typeof body !== "string" ||
        localVarRequestOptions.headers["Content-Type"] === "application/json";
      localVarRequestOptions.data = needsSerialization
        ? JSON.stringify(body !== undefined ? body : {})
        : body || "";

      return {
        url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
        options: localVarRequestOptions,
      };
    },
  };
};

/**
 * RecipesApi - functional programming interface
 * @export
 */
export const RecipesApiFp = function (configuration?: Configuration) {
  return {
    /**
     * Creates a new recipe and saves to backend.
     * @summary Create a new recipe
     * @param {RecipeRequest} body Recipe object to be created and saved.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async createRecipe(
      body: RecipeRequest,
      options?: AxiosRequestConfig
    ): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<Recipe>>> {
      const localVarAxiosArgs = await RecipesApiAxiosParamCreator(configuration).createRecipe(
        body,
        options
      );
      return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
        const axiosRequestArgs: AxiosRequestConfig = {
          ...localVarAxiosArgs.options,
          url: basePath + localVarAxiosArgs.url,
        };
        return axios.request(axiosRequestArgs);
      };
    },
  };
};

/**
 * RecipesApi - factory interface
 * @export
 */
export const RecipesApiFactory = function (
  configuration?: Configuration,
  basePath?: string,
  axios?: AxiosInstance
) {
  return {
    /**
     * Creates a new recipe and saves to backend.
     * @summary Create a new recipe
     * @param {RecipeRequest} body Recipe object to be created and saved.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async createRecipe(
      body: RecipeRequest,
      options?: AxiosRequestConfig
    ): Promise<AxiosResponse<Recipe>> {
      return RecipesApiFp(configuration)
        .createRecipe(body, options)
        .then((request) => request(axios, basePath));
    },
  };
};

/**
 * RecipesApi - object-oriented interface
 * @export
 * @class RecipesApi
 * @extends {BaseAPI}
 */
export class RecipesApi extends BaseAPI {
  /**
   * Creates a new recipe and saves to backend.
   * @summary Create a new recipe
   * @param {RecipeRequest} body Recipe object to be created and saved.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof RecipesApi
   */
  public async createRecipe(
    body: RecipeRequest,
    options?: AxiosRequestConfig
  ): Promise<AxiosResponse<Recipe>> {
    return RecipesApiFp(this.configuration)
      .createRecipe(body, options)
      .then((request) => request(this.axios, this.basePath));
  }
}
