function cov_1e1b4v4nz2() {
  var path = "C:\\NTNU\\matsmartfrontend4\\smartmat-frontend\\src\\services\\index.ts";
  var hash = "bfb49b9867f3792ff5691b711ec088cb4cc837da";
  var global = new Function("return this")();
  var gcv = "__coverage__";
  var coverageData = {
    path: "C:\\NTNU\\matsmartfrontend4\\smartmat-frontend\\src\\services\\index.ts",
    statementMap: {},
    fnMap: {},
    branchMap: {},
    s: {},
    f: {},
    b: {},
    _coverageSchema: "1a1c01bbd47fc00a2c39e90264f33305004495a9",
    hash: "bfb49b9867f3792ff5691b711ec088cb4cc837da"
  };
  var coverage = global[gcv] || (global[gcv] = {});
  if (!coverage[path] || coverage[path].hash !== hash) {
    coverage[path] = coverageData;
  }
  var actualCoverage = coverage[path];
  {
    // @ts-ignore
    cov_1e1b4v4nz2 = function () {
      return actualCoverage;
    };
  }
  return actualCoverage;
}
cov_1e1b4v4nz2();
/* tslint:disable */
/* eslint-disable */
/**
 * Freshify API Documentation
 * An API for creating and managing a household inventory and shopping list. The API is written in Java using the Spring Boot framework. The API uses a MySQL database. The API is documented using Swagger. The API is hosted using Apache. Some useful links: - [The GitLab repository](https://gitlab.stud.idi.ntnu.no/idatt2106-v23-10/smartmat-backend)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: vkbugge@hotmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
export * from "./api";
export * from "./configuration";
export * from "./models";
//# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJuYW1lcyI6WyJjb3ZfMWUxYjR2NG56MiIsImFjdHVhbENvdmVyYWdlIl0sInNvdXJjZXMiOlsiaW5kZXgudHMiXSwic291cmNlc0NvbnRlbnQiOlsiLyogdHNsaW50OmRpc2FibGUgKi9cbi8qIGVzbGludC1kaXNhYmxlICovXG4vKipcbiAqIEZyZXNoaWZ5IEFQSSBEb2N1bWVudGF0aW9uXG4gKiBBbiBBUEkgZm9yIGNyZWF0aW5nIGFuZCBtYW5hZ2luZyBhIGhvdXNlaG9sZCBpbnZlbnRvcnkgYW5kIHNob3BwaW5nIGxpc3QuIFRoZSBBUEkgaXMgd3JpdHRlbiBpbiBKYXZhIHVzaW5nIHRoZSBTcHJpbmcgQm9vdCBmcmFtZXdvcmsuIFRoZSBBUEkgdXNlcyBhIE15U1FMIGRhdGFiYXNlLiBUaGUgQVBJIGlzIGRvY3VtZW50ZWQgdXNpbmcgU3dhZ2dlci4gVGhlIEFQSSBpcyBob3N0ZWQgdXNpbmcgQXBhY2hlLiBTb21lIHVzZWZ1bCBsaW5rczogLSBbVGhlIEdpdExhYiByZXBvc2l0b3J5XShodHRwczovL2dpdGxhYi5zdHVkLmlkaS5udG51Lm5vL2lkYXR0MjEwNi12MjMtMTAvc21hcnRtYXQtYmFja2VuZClcbiAqXG4gKiBPcGVuQVBJIHNwZWMgdmVyc2lvbjogMS4wLjBcbiAqIENvbnRhY3Q6IHZrYnVnZ2VAaG90bWFpbC5jb21cbiAqXG4gKiBOT1RFOiBUaGlzIGNsYXNzIGlzIGF1dG8gZ2VuZXJhdGVkIGJ5IHRoZSBzd2FnZ2VyIGNvZGUgZ2VuZXJhdG9yIHByb2dyYW0uXG4gKiBodHRwczovL2dpdGh1Yi5jb20vc3dhZ2dlci1hcGkvc3dhZ2dlci1jb2RlZ2VuLmdpdFxuICogRG8gbm90IGVkaXQgdGhlIGNsYXNzIG1hbnVhbGx5LlxuICovXG5leHBvcnQgKiBmcm9tIFwiLi9hcGlcIjtcbmV4cG9ydCAqIGZyb20gXCIuL2NvbmZpZ3VyYXRpb25cIjtcbmV4cG9ydCAqIGZyb20gXCIuL21vZGVsc1wiO1xuIl0sIm1hcHBpbmdzIjoiOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7O0lBZVk7SUFBQUEsY0FBQSxZQUFBQSxDQUFBO01BQUEsT0FBQUMsY0FBQTtJQUFBO0VBQUE7RUFBQSxPQUFBQSxjQUFBO0FBQUE7QUFBQUQsY0FBQTtBQWZaO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0EsY0FBYyxPQUFPO0FBQ3JCLGNBQWMsaUJBQWlCO0FBQy9CLGNBQWMsVUFBVSJ9